### ISSUE TITLE
how to keep Ex fixed at boundaries?

### ISSUE THREAD

**Issue by tsikd** [Warwick-Plasma/epoch#151]
I am trying to set up a simulation like https://en.wikipedia.org/wiki/Townsend_discharge (rotated to horizontal direction) i.e. I would like to fix Ex at x_min and x_max. Please see attached fields.f90. I wrote drive_field routine that is called at half and full time steps, but it seems NOT to KEEP Ex at both ends. Please advise how to fix this issue? 
[fields.f90.txt](https://github.com/Warwick-Plasma/epoch/files/6027942/fields.f90.txt)
(i.e. how to force FIXED Ex and both ends). Thanks!

**Comment by tsikd** [comment]
also, what do you think is most matching boundary condition for fields? is it 
bc_x_min_field = open
  bc_x_min_particle = heat_bath
  
  bc_x_max_field = open
  bc_x_max_particle = heat_bath

  bc_y_min_field = open
  bc_y_min_particle = heat_bath
  
  bc_y_max_field = open
  bc_y_max_particle = heat_bath

**Comment by TomGoffrey** [comment]
I think `cpml_outflow` is closer to what you want, but I'm not sure there's a perfect match for what you're doing.

As for your `drive_field` routine, your problem is you are calling it before the boundary conditions calls. As discussed in #149 the boundary conditions will set the values for ex(0), ex(nx), so your values get overwritten.

You could try something like:

```fortran
SUBROUTINE drive_field(time)

  REAL(num), INTENT(IN) :: time
  REAL(num), PARAMETER :: ex_fixed = -5.0e4_num

  IF (x_min_boundary) THEN
    ex(1-ng:0,:) = ex_fixed
  END IF 

  IF (x_max_boundary) THEN
    ex(nx:nx+ng,:) = ex_fixed
  END IF 

END SUBROUTINE drive_field



SUBROUTINE update_eb_fields_half
  ...
  CALL update_e_field
  ! Now have E(t+dt/2), do boundary conditions on E
  CALL efield_bcs
  CALL drive_field(time+0.5_num*dt)
  ...
END SUBROUTINE update_eb_fields_half



SUBROUTINE update_eb_fields_final
  ...
  CALL update_e_field
  CALL efield_bcs
  CALL drive_field(time+dt)
  ...
END SUBROUTINE update_eb_fields_final
```

I've modified your fields routine slightly, so that it sets `ex` in all the ghostcells. I'm not sure if this is necessary, but it seemed a safer option.
