### ISSUE TITLE
runing code

### ISSUE THREAD

**Issue by mimboch** [Warwick-Plasma/epoch#174]
Hi

I can't run the code, maybe it's a problem with code version.

Thank you in advance.

![11](https://user-images.githubusercontent.com/46644633/111027928-91b85380-83f3-11eb-9583-8346c4574777.png)

**Comment by TomGoffrey** [comment]
There appears to be a problem with your input deck. Please post the deck.

**Comment by mimboch** [comment]
OK.
[input.txt](https://github.com/Warwick-Plasma/epoch/files/6135265/input.txt)

**Comment by keithbennett** [comment]
There are a few errors with your input deck. On line 73 there is a semicolon instead of a comma. That is the error that is being complained about. There is also a typo for "temp_ev" on line 75 and unbalanced parenthesis on line 109. The error messages could be a bit more helpful here. I add some changes to make them better.
