### ISSUE TITLE
Complex density profiles

### ISSUE THREAD

**Issue by OscarJakobssonLPA** [Warwick-Plasma/epoch#265]
Hi, 

When defining complex density profiles in EPOCH, we often use several lines for the definition (particularly given the limitation of maximum number of characters per line of the input deck). E.g
begin:species
  name = elec

  density = if(x lt x1, Something, density(elec))
  density = if(x lt x2, SomethingElse, density(elec))
  ...
  density = if(x lt xN, SomethingElseN, density(elec))
end:species

As additional lines are added, the computational time grows very quickly, even when those lines are part of an IF statement that has not yet been meet. Is there any reason for the slow-down, or any way to work around it other than writing it all as a very long string? 

Many thanks, 
Oscar

**Comment by Status-Mirror** [comment]
Hi Oscar,

Apologies for the incredibly late response.

I imagine this is due to the EPOCH maths parser, which isn't something that can be easily optimised. You could try a very long string, or you may find more use with the interpolate(...) function.

This is discussed here:
https://epochpic.github.io/documentation/code_details/maths_parser.html

Cheers,
Stuart
