### ISSUE TITLE
How to use constant particle weights?

### ISSUE THREAD

**Issue by gmmfarrow** [Warwick-Plasma/epoch#289]
I want to run a simulation with a varying number density, but constant superparticle weights (so the initial superparticles per cell varies in space). I tried to do this by uncommenting PER_SPECIES_WEIGHT in the makefile, but this caused strange behaviour. The number density still varied, but the particles per cell was all the same and the particle weight was just 1 (instead of the much larger number you would expect). I got identical answers when this was commented or uncommented, so I suspect it had some undefined behaviour.

What is the correct way to get all superparticles to have the same computational weight?

**Comment by Status-Mirror** [comment]
Hi @gmmfarrow,

Apologies for the incredibly late response - we're currently addressing the backlog of issues. As far as I'm aware, switching on PER_SPECIES_WEIGHT should be enough to fix all the particle weights.

If you're still around and have the input deck, I'd like to see why it wasn't generating the expected behaviour.

Cheers,
Stuart
