### ISSUE TITLE
visualisation of 3D simulation

### ISSUE THREAD

**Issue by smax520** [Warwick-Plasma/epoch#317]
Dear all,
I have a problem with visulisation the result of 3D simulation.  I`m using the Python version of the SDF reader and have no idea how to plot the plasma grid properties (fields, mass density ...). In 2D version sh.plot.auto function works very well, but it seems that there is no automatic plotting option for grid variables in 3D... 
 maybe someone can share a working version of a python script for building 3d images (for grid variables with coordinates [x[y[z]]] )? 
Or maybe someone knows if there is such a possibility in the Matlab version of the SDF reader?

**Comment by Vlasovian** [comment]
If you aren't already, try working with the raw data in SDF format (https://epochpic.github.io/documentation/visualising_output/python.html). Otherwise, VisIt is probably your best option for 3d visualisation (https://epochpic.github.io/documentation/visualising_output/visualising_sdf_files_with_llnl_visit.html)

**Comment by Status-Mirror** [comment]
Hi all,

Apologies for the delay, I'm extended the response to fully close the issue now.

I agree with Vlasovian, it probably is easier to work with the raw SDF files. I'm attaching a template for 3D plots with MATLAB, along with an extra function to make it work. I'm also attaching a plot produced by the code, using randomly generated data. The plot shows the 3D array values from two 2D slices in the centre of the xy and xz planes.

![example](https://user-images.githubusercontent.com/38282483/191920791-6ef98148-2ff8-4265-9ffd-ae278ad1399d.png)

Hopefully the plotting script is clear enough to modify, so that it may suit your needs.

Note, you need to edit these filenames so they end in ".m" - I am attaching them as ".txt" files as github does not support ".m"

[simple_3d_grid_plot_template.txt](https://github.com/Warwick-Plasma/epoch/files/9632087/simple_3d_grid_plot_template.txt)
[GetVariableSDF.txt](https://github.com/Warwick-Plasma/epoch/files/9632098/GetVariableSDF.txt)

Cheers,
Stuart
