### ISSUE TITLE
question on heat_bath

### ISSUE THREAD

**Issue by yjs0014** [Warwick-Plasma/epoch#321]
Dear All:
  I just couldn't understand the boundary condtion heat_bath. I thought this fuction is achieved via removing the particle that leaves the simulation box and injecting a hot particle meanwhile. But, there is no description about the temperature of injected particles, i.e., we don't know the temperature of heated boundary. I'm confused.

**Comment by Status-Mirror** [comment]
Hi yjs0014,

Apologies for the late response - we're making an effort to clear up legacy issues at the moment.

Your description matches the "thermal" boundary - here, outgoing particles are reflected back into the simulation window, with a momentum drawn from a thermal distribution. The temperature matches the temperature of that particle species at the boundary, according to the initial conditions.

The "heat-bath" boundary is slightly different. Before the main PIC loop starts, an injector is set-up on the boundary to match the initial species parameters on the boundary. In the ideal case, the number of particles leaving the simulation window due to thermal velocities will be balanced by an equal number returning through the injectors.

The key difference between "thermal" and "heat_bath" boundaries is that heat_bath removes outgoing particles, and thermal reflects them. This distinction is important if you have a drifting particle population.

Hope this helps,
Stuart
