### ISSUE TITLE
Focal spot size of wavelength

### ISSUE THREAD

**Issue by anecas1979** [Warwick-Plasma/epoch#346]
Dear EPOCH gurus,

When I propagate a simple laser in vacuum in 3D, I can recover from EPOCH the analytically predicted energy when beam waist diameter is 8 micron.  However, when the beam waist is 5 micron, I obtain too high energy.  Does EPOCH break down?  I think if I remember EPOCH employs the paraxial approximation but I cannot find my notes or any mention.

Thank you,

Sincerely,

Ales

**Comment by Status-Mirror** [comment]
Hi Ales,

Apologies for the delay, we're currently working through our backlog of issues.

The EPOCH field solver does not use the paraxial approximation - it simply solves Maxwell's equations. However, in order to focus a Gaussian beam, we provide an [example](https://epochpic.github.io/documentation/examples/basic_examples.html) which does assume the paraxial approximation. The idea is that if we set the boundary to be a solution, then the wave will propagate to the analytic paraxial focus.

When the beam waist becomes comparable to the laser wavelength, this methodology breaks down. The paraxial solution is no longer valid, so the laser pulse does not follow this analytic case. You may need to tweak the focus distance, or laser intensity, to get the focus properties you want.

Hope this helps,
Stuart
