### ISSUE TITLE
sdf/fortran/include folder empty

### ISSUE THREAD

**Issue by Mark-T-Kram** [Warwick-Plasma/epoch#347]
Hi in the three most recent versions(4.17.14-16) this folder sdf/fortran/include is completly empty and so does not compile when using make  COMPILER=gfortran as directed in the user manual.

**Comment by TomGoffrey** [comment]
The files within `SDF/FORTRAN/include` are created as part of the compilation of the code.

As it stands there's not enough information to diagnose your problem. Please provide complete logs of your attempts to compile the code (in a text file please), as well as details of the machine you're using, and any other relevant information.

**Comment by Mark-T-Kram** [comment]
Hi Tom,
Thank you for getting back to me, unfortunately I do not have logs, just a
screenshot which is attached.
I was attempting to compile using the Viking Computer at the University of
York.
I have since been able to get it to compile with the help of a colleague
who had a different SDF folder, I compared the two which must be from
different versions.
To solve the problem I replaced the SDF/FORTRAN folder from the 4.17.16
version with the one my colleague had.
I have attached the screenshots of the comparison where the SDf_alt folder
is the one from my colleague.

Thanks
Mark

**Comment by Status-Mirror** [comment]
Hi Mark,

Glad to hear you've solved the issue! As a former Viking user myself, I think the most likely cause of your problem was missing the --recursive flag when getting the source-code from GitHub. The SDF directory isn't actually part of EPOCH, but is its own GitHub package. 

The --recursive flag in git clone installs the GitHub project you're interested in (EPOCH) and all the projects linked to this one too (including SDF and sub-modules).

Hope this helps,
Stuart

**Comment by Mark-T-Kram** [comment]
Hi Stuart,
Thanks for the follow up, that makes sense. That will help if any of my colleagues run int similar issues.

Best wishes 
Mark Turner.
