### ISSUE TITLE
A query about the probe block

### ISSUE THREAD

**Issue by swsx1317** [Warwick-Plasma/epoch#349]
Dear developers, 

I used the epoch probe block to count the crossing charge of electrons in a plan recently, and I have a query that is the dump output results accumulate continuously from the start to the end, or just contain the particles results between the neighbour dumps? I can not find the answer in the manual, and I will be very appreciative if anyone could give me the answer, thank you so much.

Best regards,
Zhang

**Comment by Status-Mirror** [comment]
Hi Zhang,

Apologies for the delay. Each output file only contains properties for particles which have passed the probe since the previous probe dump, and not all particles which have passed the probe since the start of the simulation.

We have now addressed this ambiguity in the documentation:
https://epochpic.github.io/documentation/input_deck/input_deck_probe.html

Cheers,
Stuart
