### ISSUE TITLE
Nuclear Fusion Algorithm for EPOCH

### ISSUE THREAD

**Issue by mafshari1** [Warwick-Plasma/epoch#356]
Hello,

Recently an experiment reported fission-fusion products during the interaction of a laser pulse with thin gold foils [1]. Also, Higginson, et al [2] implemented a Pairwise Nuclear Fusion Algorithm at PIC code Chicago. Is it possible to embed such an algorithm into the epoch code?

[1] F. Lindner et al., Scientific Reports 12.1 (2022).
[2] Higginson, et al "A pairwise nuclear fusion algorithm for weighted particle-in-cell plasma simulations." Journal of Computational Physics 388 (2019): 439-453.

**Comment by denisbertini** [comment]
Hi
In order to test a new Fusion collision module for EPOCH, i will need to have
particle scattering, particle motion and fields disabled in order to guarantee  that 
- plasmas constant over all time
- the fusion products do not heat the plasma
I can switch off scattering myself modifying the code in `collisions.F90` but how to disable particle motion for example?

**Comment by denisbertini** [comment]
Ah ...
It seems that i can add `particle_tstart` to a relatively high value from the `control` block  to disable particle motion.
Am i right?

**Comment by TomGoffrey** [comment]
Assuming the fusion products are a separate species, you could just set `immobile = T` in the species block.

**Comment by TomGoffrey** [comment]
No problem.
