### ISSUE TITLE
Linear numerical heating in two majority ion simulation?  

### ISSUE THREAD

**Issue by tobiassh0** [Warwick-Plasma/epoch#375]
Hi, 

I'm running a 1d simulation of a three ion species, two majority ions and one minority in a ring-beam, the input deck is attached. I'm using version 5.0-devel and simulating a ring-beam following the example deck. 

My problem is that the majority ions (Deuterons and Tritons) linearly heat almost immediately, despite their gyro-radii being resolved (including those of the electrons). Attached is a plot of the field energies and KE of the particles to demonstrate this. We see the Magnetoacoustic cyclotron instability develop, as expected, later in the simulation with the minority ions (alpha particles) following their typical trend. But the majority ions seem to heat and electrons cool for a few cyclotron periods before the instability sets in. 

The grid is smaller than the Debye length so this is resolved, and the gyro-radii of the particles are also all resolved. The simulation is quasi-neutral as calculated by my Kappa, Lambda, Mu and Alpha coefficients. So I'm wondering why they are they heating/cooling? 

Thanks

[input.txt](https://github.com/Warwick-Plasma/epoch/files/8974870/input.txt)
![energy_densities](https://user-images.githubusercontent.com/67916510/175505510-0aa84bc8-e43d-48ae-a0fe-2918b56c3ad9.jpeg)

**Comment by Status-Mirror** [comment]
Hi @tobiassh0 

Apologies for the delay in getting back to you, we're currently trying to clear our issue backlog. Is this still an issue?

I'm afraid I don't know much about these systems, but if this is a numerical problem, the magnitude of the heating will depend on a few parameters. You can reduce the numerical heating in a simulation by:
- Increasing the number of cells
- Adding more macro-particles per cell
- Adding the line "smooth_currents = T" to the input deck
- Uncommenting the line "#DEFINES += $(D)PARTICLE_SHAPE_BSPLINE3" in the Makefile, running "make clean" and then remaking the code.

If the heating magnitude doesn't change as you alter these parameters, then this isn't a normal numerical heating problem. Otherwise, you can adjust these parameters until you get convergence.

Hope this helps,
Stuart

**Comment by tobiassh0** [comment]
Hi Stuart, 

This is no longer an issue. 

Thanks,
Tobias
