### ISSUE TITLE
send/receive performance

### ISSUE THREAD

**Issue by elhadjm229** [Warwick-Plasma/epoch#396]
Hi developers

I run epoch2D without collisions in my small cluster with 5 WS connected via 1 Gbs TCP, I use OpenMPi 4.0, Gfortran and BeeGFS.
I followed the transfer of data during execution via "System Monitor"; I noticed that the send/receive reaches its maximum during the writing of the output file but during the phase of calculations the flow is weaker.
When I increase the number of cells or the number of particles per cell, the send/receive transfer therefore becomes weaker during the calculation phase but remains the same when writing to the output file (maximum). I tried to tune TCP and OpenMPI parameters but without improvement.
is this behavior normal?
if not, is there a way or parameters to adjust to improve performance.
I need your help

Thanks in advance

**Comment by Status-Mirror** [comment]
Hi Elhadjm, 

Another developer may swoop in and correct me, but as far as I'm aware, I/O operations are usually the slowest part of the code. This is done using the SDF libraries, which are also developed at Warwick. All cells and particles in a processor need to be written to a file.

During calculations, the code only transfers ghost cell fields, and particles which pass processor boundaries, which might explain the difference you're seeing? I would have expected a greater ppc to have a greater computational cost with the MPI routines, as more particles would need to be passed.

Are you experiencing any problems running the code to completion?

Cheers,
Stuart

**Comment by elhadjm229** [comment]
Hi Stuartthank you for your replyyes I understood the difference between the calculation phase and the writing phase in the output filebut what seems odd to me is the decrease in throughput with the increase in the number of cells or number of particles per cell. for example :* for 1000x1000 cells and 20 ppc the throughput is around 100 to 120 MBs (∼1 Gbs) during writing and around 25 MBs (∼200 Mbs) during computing.* for 1000*1000 cells and 50ppc the throughput is the same around 100 to 120 MBs during writing but around 17 MBs during computing.* for 6000*8000 cells and 50ppc the throughput is the same around 100 to 120 MBs during writing but around 6 to 8 MBs during computing.- whereas for me: more cells and more particles mean more data to transfer, so the throughput will be higher. I want to understand !!
thank you in advance

Elhadj.DAHIChief Medical Physicist; CLCC Tlemcen
Orcid : 0000-0002-2425-4713 

    Le lundi 10 octobre 2022 à 15:42:03 UTC+1, Stuart Morris ***@***.***> a écrit :  
 
 


Hi Elhadjm,

Another developer may swoop in and correct me, but as far as I'm aware, I/O operations are usually the slowest part of the code. This is done using the SDF libraries, which are also developed at Warwick. All cells and particles in a processor need to be written to a file.

During calculations, the code only transfers ghost cell fields, and particles which pass processor boundaries, which might explain the difference you're seeing? I would have expected a greater ppc to have a greater computational cost with the MPI routines, as more particles would need to be passed.

Are you experiencing any problems running the code to completion?

Cheers,
Stuart

**Comment by Status-Mirror** [comment]
Hi Elhadj,

I've spoken to a few different developers, and I'm not sure we can explain the drop-off you're seeing. Our ability to support running on private clusters is limited - the behaviour you're seeing may be normal for your system.

To answer a question from your first post, I don't believe there are any parameters in the code which may improve performance. You do have the ability to manually overwrite the domain decomposition though. For example, if you want a grid of 10x5 MPI ranks instead of the default, then you may use the keys: nprocx, nprocy in 2D. These are control block variables, which are explained here:
https://epochpic.github.io/documentation/input_deck/input_deck_control.html

Aside from this, I don't know of any input block parameters which can change the MPI behaviour (aside from the load balance, but that doesn't seem to be the cause of your concern).

Sorry we couldn't be more helpful,
Stuart
