### ISSUE TITLE
Spectrum of laser pulses

### ISSUE THREAD

**Issue by TrumeAAA** [Warwick-Plasma/epoch#403]
Hi,

Is it possible to set the spectrum of the laser pulses directly ?
Any help or suggestion will be helpful.

Thanks.

**Comment by Status-Mirror** [comment]
Hi @TrumeAAA 

Currently you can't directly output a Fourier transform of the laser. At present, the best method to find the laser spectrum at a given time would be to make an output block which gives field measurements each step. For example:

```
begin:output

  name = spectrum_1     # The first dump will have filename spectrum_10000.sdf
  nstep_snapshot = 1    # Print fields every step

  # Consider a window around 25 fs
  time_start = 25.0e-15 - 5.0e-15 
  time_stop = 25.0e-15 + 5.0e-15

  # Fields to print
  ex = always
  ey = always 
  ez = always
  bx = always
  by = always
  bz = always

end:output
```

This block will output the field values every time-step around a time of interest (set to 25 fs here). From here, the intensity is equal to 1/mu_0 * |E x B|. Hence, you can calculate the intensity in each cell at each time-step. By taking the Fourier transform of the intensity as a function of time in each cell, you can deduce the laser spectrum at this time. 

In this version, you would need a new output block for each time of interest. We are currently developing a new output style called accumulators, which will allow regular dumps in a single output block.

Final point: because we are using one named output block, we must name all output blocks in the simulation - including your original one (unless you were already using multiple output blocks).

Any further questions, feel free to ask!

Cheers,
Stuart

**Comment by Status-Mirror** [comment]
P.S. You may be able to skip a step by outputting the Poytning flux instead of the raw fields:

```
begin:output

  name = spectrum_1     # The first dump will have filename spectrum_10000.sdf
  nstep_snapshot = 1    # Print fields every step

  # Consider a window around 25 fs
  time_start = 25.0e-15 - 5.0e-15 
  time_stop = 25.0e-15 + 5.0e-15

  # Fields to print
  poynt_flux = always

end:output
```

This will give you the Poynting flux in the x, y, and z directions, so the total intensity at this point would be the magnitude of this vector. Then, once you have the intensity each time-step, you can find the laser spectrum in each cell by performing a Fourier transform as above.
