### ISSUE TITLE
How to correctly set the mesh precision(nx，ny，nz) and the number of particles filled (npart_per_cell) ?

### ISSUE THREAD

**Issue by xinyingyixia** [Warwick-Plasma/epoch#414]
In my recent experiments, I find that the set of nx, ny, nz and npart_per_cell can make a big difference to the output of the information  of the field. So I just want to know that if there are some skills can help me correctly set these parameters to get the right output. I will appreciate it if someone shares his/her experience.

**Comment by Status-Mirror** [comment]
Hi @xinyingyixia 

We can help you get the simulation up and running. It would be helpful if you could attach the input deck you're using, and let us know your desired outcome.

Cheers,
Stuart

**Comment by Status-Mirror** [comment]
To get a good result, you'll usually want your cell size to be at least as big as your Debye length. For a laser with a0=4, let's use ponderomotive scaling to estimate a mean electron energy of <ke>~a0mc2, or about 2 MeV. Combining this with your number density of 1e25/m3, I estimate a Debye length of around 3 micron.

However, we also need to resolve the laser wavelength - typically at least 20 cells per wavelength. I think a good starting point would be nx = 3000, ny = nz = 1800. Finally, we typically use ~128 PPC in our higher density runs, but perhaps you don't need so high.

These proposed parameters are much higher than what you're currently using. 3D simulations are very expensive, which is why you often find 2D in the literature. Perhaps there are some shortcuts you can take...

- Moving window: You can simulate a smaller domain which moves with your laser wavefront. Cells are added to the end of the simulation window with new target particles, and deleted from the front. This limits the number of particles simulated each time step.

- Convergence tests: You may not need the parameters I detail above. A good way to check how many resources you need is to set up a simulation with a significantly smaller grid (maybe 10x10x10) without the laser, then increase the ppc until you find a convergence in final particle temperature. To do this accurately, you'll need to give particles an initial temperature based on the temperatures they're likely to reach in the full simulation. This is a good way of measuring the numerical heating for a set of parameters - you may not get full convergence, but you can minimise noise to an acceptable level.

- If convergence is too computationally expensive, you can always switch to epoch2d for a significant speed-up.

Hope there's some useful information in there!
Stuart

**Comment by xinyingyixia** [comment]
Thank you @Status-Mirror . You are a nice man.
