### ISSUE TITLE
What does “4.18-hybrid” branch mean？

### ISSUE THREAD

**Issue by smallrainbow** [Warwick-Plasma/epoch#415]
Dear developers,

What is the difference between 4.18-hybrid and your official 4.18 version?
Thank you very much!

@Status-Mirror 

Best regards,
Zhongwei

**Comment by Status-Mirror** [comment]
Hi Zhongwei,

I made a hybrid-PIC code for modelling intense laser-solid interactions, discussed here: https://aip.scitation.org/doi/abs/10.1063/5.0055398

This uses a modified field solver, which treats the target as a background field, and modifies the fast electrons travelling through. Fast electrons are injected, and no actual laser is modelled. It gives a significant speed-up, and allows large-scale, multi-picosecond, 3d modelling.

The original code with documentation is hosted at GitHub.com/status-mirror/epoch and we were wondering if we should add it to the main Warwick branch. It's quite a big addition though, and we've been prioritising other branches lately, like collisional Ionisation and collisions. They will be released in 4.19, before the end of this year.

If you're interested in using the hybrid code, I'm open to support that work too.

Cheers,
Stuart

**Comment by bzdjordje** [comment]
@Status-Mirror 
Hi Stuart, is it possible to get access to the hybrid version of Epoch? We are doing laser-solid interactions and I am very interested in your work.

**Comment by Status-Mirror** [comment]
Hi @bzdjordje

The Hybrid version is currently hosted on a separate repository. Because it is a large extension, we were only going to add it to EPOCH if there was enough demand for it. It's currently open source, and you can install it using the following commands:

```perl
  git clone https://github.com/Status-Mirror/epoch.git
  cd epoch
  git clone --recursive https://github.com/Warwick-Plasma/SDF.git
```

The hybrid code takes the same keys as the existing EPOCH code, but there are a few new physics packages and input deck blocks. A brief code description is provided in: https://doi.org/10.1063/5.0055398 and detailed documentation is given in the `hybrid_documentation` folder, along with example input decks for the benchmarks covered in the documentation.

Hope this helps,
Stuart

**Comment by bzdjordje** [comment]
@Status-Mirror 
Terrific, thank you!
