### ISSUE TITLE
Temperature not dumping at restart

### ISSUE THREAD

**Issue by tobiassh0** [Warwick-Plasma/epoch#428]
Hi, 

I'm trying to dump temperature at restart dumps _only_, but the following input deck doesn't dump temperature at all. I've tried altering the force_first flag and restart_dump_every but it seems that as soon as temperature = restart + species it no longer outputs.

Best,
Tobias
[input.txt](https://github.com/Warwick-Plasma/epoch/files/10196027/input.txt)

**Comment by Status-Mirror** [comment]
Hi Tobias,

I think EPOCH is getting a little confused because temperature isn't a restart variable. Maybe you should set it to only output on "full" dumps, and make full and restart dumps occur on the same time-steps.

Recently we've been suggesting the use of multiple named output dumps. Here you can have different variables output at different rates, and you can make certain output blocks control restart dumps with "restartable". The full documentation for these named blocks is given here: https://epochpic.github.io/documentation/input_deck/input_deck_output_block.html

Cheers,
Stuart
