### ISSUE TITLE
information about parent electron of emitted photon

### ISSUE THREAD

**Issue by ktangtar** [Warwick-Plasma/epoch#474]
Hi,

For the qed module, photons are emitted from accelerated electrons.  
Can a feature be added, such that information about that emitting electron is tracked in the photon data?  For example, the ID, $\gamma$, $\eta$, momentum, or fields on the electron that emits the photon?

Regards,
Kavin Tangtartharakul

**Comment by Status-Mirror** [comment]
Hey Kavin,

All these things are possible - but these would be a lot of new diagnostics, and you may want more in the future. I'm wondering if it would be more useful to the general EPOCH user-base if we produced detailed documentation on how to create new particle diagnostics, instead of having to wait for the developers to get a free moment?

There are a few stages to intoduce a new particle variable, make it interact with MPI correctly, and setting up an iterator to output it - but the individual stages aren't very difficult.

Would this be useful to you?

Cheers,
Stuart

**Comment by ktangtar** [comment]
Yes, that would be helpful to me, learning what changes to epoch are required to output new variables.

**Comment by Status-Mirror** [comment]
Hi Kavin,

Sorry for the delay. We have added a [new page](https://epochpic.github.io/developer/extensions/new_particle_variable.html) to our developer documentation which explains how to do this. The particular example on this page explains how to output the emitting electron gamma factor.

You also requested some other variables. These instructions will make sense once you have read the new page on our website:
- For ID, I wouldn't attempt this until EPOCH v4.19.2. ID values are only set when EPOCH tries to write ID to the SDF file. You could make a variable for storing the emitting electron ID, but you may just be storing 0's.
- For momentum, the best place to set this is also in `generate_photon`, as these can be accessed from the generating electron properties
- For $\eta$, I would make a new module variable for $\eta$, set the value of this variable in the `calculate_eta` subroutine, and then assign this value to your photon macro-particle in the `generate_photon` subroutine.
- You could also make new module variables for the fields on the electron. These are calculated in photons.F90 in the `field_at_particle` subroutine.

Hope this helps,
Stuart

**Comment by ktangtar** [comment]
Thank you! It looks like pretty detail documentation, I will try it out.

**Comment by Status-Mirror** [comment]
Excellent news! I'm glad the documentation is clear enough to be used.
