### ISSUE TITLE
what should be the quantity of electron energy absorbing from the laser compared to other particles?

### ISSUE THREAD

**Issue by mimboch** [Warwick-Plasma/epoch#495]
Hello
Does it correct to see that the laser energy converted into Ek of protons higher than Ek of electrons for the same target .
 Any help or clarification please.
Thank you in advance

**Comment by Status-Mirror** [comment]
I think this would depend on your simulation.

It may be a good idea to run a simulation without the laser present to see if you have self-heating in the system (when particles gain energy non-physically due to using cells which are too large, or using too few particles per cell).

Cheers,
Stuart

**Comment by mimboch** [comment]
Hello
I used a cells not large (10nm) and 64 particles/cell.
I want to know if protons can gain more energy than electrons during the acceleration process. Or the electrons energy should higher all time rather than protons.
Thanks.

**Comment by Status-Mirror** [comment]
In my experience, I would imagine the electron population should absorb more laser energy. We may be thinking about different systems though. Do you have an input deck which is leading to higher proton energies?

**Comment by mimboch** [comment]
Yes , I'm attaching you my input.
I think that the problem is in the calculation of conversion efficiency into particles.
To calculate the energy laser converted in kinetic energy  of particles, I took the ratio of Ek/ Utot
Utot = UE+UB ( electromagnetic energy )
 Ek = np.sum(np.multiply(ekbar_particle,den_particle))*dx*dy

[input.txt](https://github.com/Warwick-Plasma/epoch/files/11542890/input.txt)

**Comment by Status-Mirror** [comment]
For absorption, you may find it more useful to add:

```
absorption = always
```

to your output block (see [here](https://epochpic.github.io/documentation/input_deck/input_deck_output_block.html)). This tracks the total amount of laser energy injected into your simulation by each dump-time. Your `Utot` would be the total EM energy present in the simulation at a given time - it doesn't tell you how much laser energy has gone into the particles.

I also think there will be some noise in the lower energy particles, especially since they start at 0 temperautre. Maybe it would be better to consider particles above a certain energy (say 100 keV). You can calculate the energy per macro-particle using:

$E_k = \left(\sqrt{(p_x^2 + p_y^2 + p_z^2)c^2 + m^2 c^4} - mc^2\right)w$

for a macro-particle, where $m$ is the mass of a single particle within the macro-particle, and $w$ is the macro-particle weight. Then sum these for particles above a threshold, and divide by the number given by the "absorption" output. This should eliminate the noise which may be present in the `ekbar` output.

Hope this helps,
Stuart
