### ISSUE TITLE
The code cannot parse the input deck sufficiently to run.

### ISSUE THREAD

**Issue by lijiangdong1999** [Warwick-Plasma/epoch#521]
Hello everyone. 
I want to use epoch to simulate PWFA driven by proton and heavy ion beams. I have already installed epoch and edit an input file, which is attached. When I ran it, epoch told me “ Not all required elements of input deck specified. Please fix input deck and rerun code”. Then I checked the “desk.status” file, I can see two loops of my simulation, so I don’t know what’s the meaning of its warning. Can you help me to check the input file I attached?
Thanks a lot.
[input.deck.txt](https://github.com/Warwick-Plasma/epoch/files/11904642/input.deck.txt)
[deck.status.txt](https://github.com/Warwick-Plasma/epoch/files/11904643/deck.status.txt)

**Comment by ktangtar** [comment]
Is it the number of particles for each specie?  I skimmed over the input deck and didn't seem like it was specified.

**Comment by lijiangdong1999** [comment]
I used "nparticles_per_cell = 10000*500*500" for "Rubidium and Electron" and "nparticles = 10000000" for "Proton", but it doesn't work.

**Comment by lijiangdong1999** [comment]
I used "nparticles_per_cell = 10000*500*500" for "Rubidium and Electron" and "nparticles = 10000000" for "Proton", but it doesn't work.

> Is it the number of particles for each specie? I skimmed over the input deck and didn't seem like it was specified.

**Comment by Status-Mirror** [comment]
Hey @lijiangdong1999,

I think there's some confusion because your `input.deck` doesn't match your `deck.status` file. In the deck you sent, the lines which tell the code how many particles to initialise the simulation with have been commented out. However, even when you include these lines, the deck does not run.

The main issue with this deck is the `maxwell_solver = custom` line. This implies you want to use a high-order field-solver using a custom stencil, and the code looks for a corresponding stencil block which is missing here. I would advise removing this line, to use the basic Yee maxwell solver. Documentation on the higher order stencils can be found in the [control block](https://epochpic.github.io/documentation/input_deck/input_deck_control.html) section of the website, if you really want to use these.

Hope this helps,
Stuart

**Comment by lijiangdong1999** [comment]
> Hey @lijiangdong1999,
> 
> I think there's some confusion because your `input.deck` doesn't match your `deck.status` file. In the deck you sent, the lines which tell the code how many particles to initialise the simulation with have been commented out. However, even when you include these lines, the deck does not run.
> 
> The main issue with this deck is the `maxwell_solver = custom` line. This implies you want to use a high-order field-solver using a custom stencil, and the code looks for a corresponding stencil block which is missing here. I would advise removing this line, to use the basic Yee maxwell solver. Documentation on the higher order stencils can be found in the [control block](https://epochpic.github.io/documentation/input_deck/input_deck_control.html) section of the website, if you really want to use these.
> 
> Hope this helps, Stuart
Dear Stuart,

Thanks a lot for your help. Now it works without errors. I will continue my simulation of PWFA.

Sincerely,
Jiangdong Li
