### ISSUE TITLE
Ionisation didn't work

### ISSUE THREAD

**Issue by 2018-2025** [Warwick-Plasma/epoch#547]
Dear sir, I found Ionisation didn't work in my input.deck. I used newest version EPOCH 4.19. 
[input.txt](https://github.com/Warwick-Plasma/epoch/files/12462258/input.txt)

**Comment by Status-Mirror** [comment]
Thanks for bringing this to our attention! There are two mistakes in your input deck:

- You use `use_collisional_ionisation` instead of `collisional_ionisation`
- You use `use_multi_photon` instead of `use_multiphoton`

These mistakes weren't your fault, as we had typos in our documentation. These are now fixed, and the ionisation section of the [species block](https://epochpic.github.io/documentation/input_deck/input_deck_species.html) documentation now has the correct versions.

Cheers,
Stuart

**Comment by 2018-2025** [comment]
Thank you very much, I have successfully solved it through your help!
