### ISSUE TITLE
The value of the laser tail is not zero

### ISSUE THREAD

**Issue by 2018-2025** [Warwick-Plasma/epoch#551]
Does anyone know why the value of the laser tail is not zero?
![image](https://github.com/Warwick-Plasma/epoch/assets/128032365/b64bb39d-f3db-48f6-9b72-4c2120712c44)
![image](https://github.com/Warwick-Plasma/epoch/assets/128032365/27898477-5a7d-4d29-9c6c-e7d1f7cce72c)

**Comment by Status-Mirror** [comment]
Hey @2018-2025,

This is an expected numerical artefact using the EPOCH field-solver method. I wouldn't expect the field to drop exactly to zero after the pulse.

More details on one of the field-solver implementations is given [here](https://epochpic.github.io/developer/core_structure/field_solver.html).

Hope this helps,
Stuart

**Comment by 2018-2025** [comment]
> 嘿@2018-2025,
> 
> 这是使用 EPOCH 场求解器方法得到的预期数值结果。我不认为脉冲后磁场会完全降至零。
> 
> [此处](https://epochpic.github.io/developer/core_structure/field_solver.html)给出了有关场求解器实现之一的更多详细信息。
> 
> 希望这有帮助， 斯图尔特

Thank you for your help!

**Comment by 2018-2025** [comment]
> Hey @2018-2025,
> 
> This is an expected numerical artefact using the EPOCH field-solver method. I wouldn't expect the field to drop exactly to zero after the pulse.
> 
> More details on one of the field-solver implementations is given [here](https://epochpic.github.io/developer/core_structure/field_solver.html).
> 
> Hope this helps, Stuart

Sir, I wonder if there is any way to drop exactly to zero after the pulse, because it will influence my diagnosis.

**Comment by Status-Mirror** [comment]
There is no method I am aware of for reducing these fields to exactly zero.

Particle-in-cell codes are generally quite noisy. If your diagnostics are sensitive to small numerical artefacts, I don't think the particle-in-cell method would be appropriate.

If you need to use a particle-in-cell code, I think it would be easier to modify your diagnostics instead of trying to remove the field noise.

Sorry I couldn't be more helpful,
Stuart
