### ISSUE TITLE
Areal density

### ISSUE THREAD

**Issue by mimboch** [Warwick-Plasma/epoch#566]
Hello every one
I received a referee's comment suggesting that I run more simulations to calculate the areal density (thickness * density). I'm not sure how to use it. Should I simply input it into the deck for a specified thickness, and which density should I use , the initial electron density?

Thank you so much for any help or information.

**Comment by Status-Mirror** [comment]
Hey @mimboch,

It's hard to know what the referee wants without context. You can output the number density from the simulation at any point using `number_density = always` in an output block.

The number of real particles in a cell is given by the number density, multiplied by the cell size $\Delta x\Delta y \Delta z$. In `epoch1d` and `epoch2d`, the missing dimensions have cell sizes of 1m. To calculate an areal density, choose a 3D volume built from some cross-sectional area $A$, and length $L$, and calculate the total number of particles in that volume. Divide this number by $L$ to obtain the areal density of the simulation region covered by $A$.

Hope this helps,
Stuart

**Comment by mimboch** [comment]
Hello,
thank you for your reply.

I'm attaching you the referee comment, to be honest I didn't understand what he wants  me to do.

[TURKI comments.docx](https://github.com/Warwick-Plasma/epoch/files/12895330/TURKI.comments.docx)

**Comment by Status-Mirror** [comment]
So if I'm reading this right...

Your paper identifies lithium-3+ as the best target for accelerating _protons_, but they think you haven't fully considered areal density. They say that areal density is the most important feature when choosing a target, so maybe you should simulate targets with _different_ materials, but the _same_ areal density.

You find the best target thickness for lithium, which has a certain density. What if you took, say, a carbon target of an equivalent areal density? It would be a thinner target, because carbon is more dense than lithium. If the referee is right, and areal density is the only important factor, then there should be no difference between the lithium and carbon targets if you set thicknesses which make the areal densities match. If you are right that lithium is the best target, you should still get better proton acceleration even if the areal densities of the two are the same.

P.S.: I am not the referee

**Comment by mimboch** [comment]
Yes, yes you're right.

Thank you so much for your feedback.
