### ISSUE TITLE
Typical density profile

### ISSUE THREAD

**Issue by laxmisubramanyam** [Warwick-Plasma/epoch#581]
Dear Team Epoch,  I am looking for some specific density profile in the code. I want to simulate a non-uniform density profile, both along the longitudinal as well as transverse direction. The profile is very similar to the attached figure. Any help would be very appreciable. 

Best regards,
Laxmi 

<img width="572" alt="Density_profile" src="https://github.com/Warwick-Plasma/epoch/assets/142707192/ce35927c-c8bb-49d0-ae5b-e042f7e8934a">

**Comment by Status-Mirror** [comment]
Hey Laxmi,

We have some examples on how to load various particle distributions on our [basic examples](https://epochpic.github.io/quickstart/basic_examples/particle_load.html) page.

If you have a density value for each cell, you might want to try a file-loading method to get an exact match. Otherwise, you might want to approximate it using [maths parser](https://epochpic.github.io/documentation/code_details/maths_parser.html) expressions.

If you choose the maths parser option, you may find this input deck to be a helpful starting point:

```
begin:control
    nx = 500
    ny = 500
    t_end = 1.0e-15
    x_min = 0
    x_max = 20e-6
    y_min = 0
    y_max = 700e-6
    stdout_frequency = 100
    npart = 10 * nx * ny
end:control

begin:boundaries
    bc_x_min = open
    bc_x_max = open
    bc_y_min = open
    bc_y_max = open
end:boundaries

begin:constant
    x0 = 5.0e-6
    x1 = 15.0e-6
    y0 = 0.0e-6
    y1 = 550.0e-6
    dens_peak = 1.0e20
    dens_x_max = x0 + (x1 - x0) / y1 * y
    dens = dens_peak / dens_x_max * (dens_x_max - x)
end:constant

begin:species
    name = Electron
    mass = 1.0
    charge = -1.0
    frac = 0.8
    density = if ((y gt y0) and (y lt y1) and (x lt dens_x_max), dens, 0)
    temp_ev = 1000
end:species

begin:species
    name = Carbon
    mass = 22033.0
    charge = 6.0
    frac = 0.2
    density = density(Electron) / 6
    temp_ev = 1000
end:species

begin:output
    dt_snapshot = t_end
    number_density = always
end:output
```

![test](https://github.com/Warwick-Plasma/epoch/assets/38282483/a28ec580-562a-4be9-80f5-ac5ccfa4e1c5)

Hope this helps,
Stuart

**Comment by laxmisubramanyam** [comment]
Dear Stuart, thanks for your kind help. It is very helpful for me. This is exactly what I was looking for. 

Thank you again.

Best regards,
Laxmi
