### ISSUE TITLE
Question about restarting the simulation

### ISSUE THREAD

**Issue by zhangli28** [Warwick-Plasma/epoch#600]
Dear @Status-Mirror, 

I have a question regarding restarting the code from dumped files. 

``
restart_dump_every = 0  
``
implies that the code can be restarted from any of the dumped files. And

``
restart_dump_every = -1
``
implies no resatable file except first (if final is still not reached due to exceeding the allowed wall time on supercomputer)

Is it possible to make every "nth" file to be restartable (nth may be every 10th or 20th file)?

Thank you.

Best regards,
Zhang

**Comment by Status-Mirror** [comment]
Hey Zhang,

Yes, you have read the documentation right. It should be pretty obvious which files are restart dumps, because they'll be significantly larger than the other output files.

Some examples of other ways to restart the simulation are given on our [basic examples page](https://epochpic.github.io/quickstart/basic_examples/restart_example.html).

Cheers,
Stuart

**Comment by zhangli28** [comment]
Dear @Status-Mirror,

Thank you for the help.

best regards,
Zhang
