### ISSUE TITLE
 Effect of laser on external magnetic field

### ISSUE THREAD

**Issue by 2018-2025** [Warwick-Plasma/epoch#608]
Sir, I found that as the laser gets closer to the external magnetic field(set by fields block), the magnetic field undergoes some strange changes if the external magnetic is perpendicular to the laser. As the picture shows.
![image](https://github.com/Warwick-Plasma/epoch/assets/128032365/53e3d47e-64bc-4b43-b65a-8bc8deabe37a)
[input.txt](https://github.com/Warwick-Plasma/epoch/files/13648279/input.txt)

**Comment by Status-Mirror** [comment]
Hey @2018-2025,

I think this is expected behaviour. You initialise the simulation with a region of high magnetic field, but the `fields` block only sets up **initial** fields. Once the simulation has loaded these fields, they will evolve according to Maxwell's equations. The sharp gradient of magnetic fields at x = 20 $\mu m$ will set up a strong electric field, which will in turn drive the magnetic diffusion you see here. I think you would find the same result in a simulation without the laser.

At present, EPOCH does not support the existence of unchanging external magnetic fields.

Hope this helps clear things up,
Stuart

**Comment by 2018-2025** [comment]
Thank you  for your kindness and expertise. I truly appreciate it.
