### ISSUE TITLE
Argument to "find value from table alt"

### ISSUE THREAD

**Issue by pengfan2** [Warwick-Plasma/epoch#662]
Dear developers,
       I would like to ask why an error occurred:"Argument to "find value from table alt" outside the range of the table. Using truncated value". What impact will it have.How should I modify it。Could this be a bug?（epoch-4.17.10），I hope to receive your help！

**Comment by Status-Mirror** [comment]
Hey @pengfan2,

You're using a version of EPOCH which is a little out of date - we've extended the range of a few tables since v4.17.10.

This error appears when you use certain physics packages. An example would be QED emission (non-linear Compton scatter): `find_value_from_table_alt` looks up the energy of an electron which is currently radiating, and randomly draws a photon energy from a distribution. If your electron energy is above or below the range given in the distribution, this warning will be triggered. The electron still radiates the photon, but it is drawn from the last-known distribution (e.g. if electron energy is too high, EPOCH uses the highest known emission spectrum, scaled to current electron energy).

There isn't anything to do about this error, it's just a warning about the limits of the model. You could switch to the more recent version for more complete tables, but I still expect this warning message to trigger. The majority of electrons should behave within the known limits of the problem.

Hope this helps,
Stuart

**Comment by pengfan2** [comment]
Thank you for taking the time out of your busy schedule to answer my questions, thank you very much！
