### ISSUE TITLE
Self generated electric/magnetic field by a room temp plasma

### ISSUE THREAD

**Issue by Khatua03** [Warwick-Plasma/epoch#663]
Dear All,
I am working with a room temp plasma of number density 5.85e28 m^-3 (Temp= 0.025 eV). After distribution of the electrons in the simulation window, it is generating an electric field of 1e9 V/m by itself without applying any external electric field. I am using 1 nm^2 cell size with 100 ppc. Can anyone suggest me how to tackle this issue? I am using open boundary conditions and my structure size is 100nm x 200nm with a simulation window of 1 micron x 4 micron.

Thank you.
Regards,
Durga Prasad Khatua

**Comment by Status-Mirror** [comment]
Hi Durga,

I would expect the open boundaries are the problem. When a macro-particle passes the boundary, it is deleted and leaves a net charge in your simulation window. Since there's no mechanism for electrons to return, your simulation domain gets gradually more charged over time.

I think this problem may be less noticable if you switched to periodic boundary conditions.

Cheers,
Stuart

**Comment by Khatua03** [comment]
Hi Stuart,
Thanks for the quick response. 
From this simulation, after plotting the electron density at different times, I can see that at this temperature (0.025 eV), electrons are not flying out of the structure. Still, it generates an electric field of the order of 1e8 V/m inside the structure. As the simulation time increases, the electric field piles up at the boundaries of the structure (in this case, the Ey component). I wonder if this is correct or not. Can you please suggest if there is any other method to tackle this other than using the periodic boundary condition? I am also attaching my input.deck file.
![image](https://github.com/Warwick-Plasma/epoch/assets/63596383/a97ab83a-6ab2-4119-96ab-e7ad127becb3)
![image](https://github.com/Warwick-Plasma/epoch/assets/63596383/6144d3e1-ba53-4a93-9d32-d5399fc2948a)
![image](https://github.com/Warwick-Plasma/epoch/assets/63596383/08937d34-201f-4bab-a442-46baf773d33a)
![image](https://github.com/Warwick-Plasma/epoch/assets/63596383/b98bdef9-9633-4151-85d4-832e93b2b5ad)
[input.txt](https://github.com/user-attachments/files/15534947/input.txt)


Thank you.
Regards,
Durga Prasad Khatua.

**Comment by Status-Mirror** [comment]
Hey Durga,

Due to macro-particle shape effects, the perceived density on the edges is lower. Macro-particles inside the simulation can project  their weight to cells outside the simulation window, but there are no particles outside projecting inwards to balance this weight-loss. As a result, you can see a reduced macro-particle density on the edges, which will be observed by the field solver, and could be responsible for the boundary fields you see.

As for the internal fields, I believe you're seeing self-heating. At 0.025 eV, you have a very cold plasma - I'm not sure how feasible it would be to model this with a PIC code. I think the resolution you would need to prevent self-heating may be prohibitavely expensive. Check out our [self heating](https://epochpic.github.io/quickstart/basic_examples/particle_load.html#self-heating) demo for more information.

Cheers,
Stuart

**Comment by Khatua03** [comment]
Dear Stuart,
Thank you so much for the insight. I can understand the macroparticle distribution, which may lead to a boundary field. 
For checking self-heating, I followed the procedure provided in the manual. In the simulation, I am also using the smooth current, bspline macro particle shape function. After extracting the peak temperature of electrons at different time steps, I found that the peak temperature was not varying much. For your reference, I attached the plot of max electron temp vs time. Besides, for Debye length, from my understanding, I think we consider the electron temperature after interaction with the laser, which in my case will be around 1863 eV, corresponding to a Debye length of 1.3 nm. Here, I have considered the initial electron density for calculating Debye length. I have also come across several articles which used room-temperature as the initial electron temp in the PIC simulation using EPOCH. What is your view on this?

![image](https://github.com/Warwick-Plasma/epoch/assets/63596383/1083ef2f-d48d-4c69-810a-970a1571baf5)

With best regards,
Durga Prasad Khatua.

**Comment by Status-Mirror** [comment]
Hey Durga,

Sorry for the delay. A plasma at 1863eV temperature is more suitable for PIC modelling, so it's sensible to prevent self-heating here. If you aim to suppress self-heating at this temperature, then the plasma will still self-heat from your lower starting temperature.

You are right, and I have seen many papers which start from a room temperature "plasma" - especially in laser-solid simulations. This might not be such a problem though. People might argue that since we self-heat to plasma temperatures anyway, as long as this self-heat temperature is lower than the final plasma state, then this is fine as we never get unphysically hot. The rise from room-temperature to hot-plasma would still be wrong, but you may argue that this process doesn't affect the physics you're interested in (e.g., the acceleration of hot electrons in a laser field).

For those interested in the specific details of a room-temperature target heating to a hot plasma state, I think this is more the domain of hydro-codes than PIC simulations. It's not unreasonable to suggest that if you're using PIC codes, you're probably interested in something which isn't strongly related to background temperature rises. Provided the background temperature never exceeds the final physical temperature (no unending self-heating) then this might be okay. I still think it would be better to initialise the simulation at a more sensible temperature though, instead of relying on self-heating to reach the plasma state.

This is just my opinion on the subject, and others may disagree on the usefulness of starting a PIC simulation at a cold temperature. Hope the discussion helps though,
Stuart
