### ISSUE TITLE
Equations dominating generated EM field from particles, in 1D PIC

### ISSUE THREAD

**Issue by sudoriente** [Warwick-Plasma/epoch#680]
Dear sir,

I've been trying to understand which equations govern and update the EM field from moving particles for several days (without any energy sources). However, the equations I know can't exactly explain the EM field intensity that I obtained from a 1D PIC simulation.

Simulation conditions:

Single macro electron particle (npart 1, placed at zero on the X-axis, temperature 100 eV, density 1.0e14, charge -1, mass 1)
30 µm simulation window size, nx 15000, simulation time 100 fs (update data every 10 fs)
Boundaries: open

The most confusing point:
This 1D PIC simulation gave me a plot of the Ex electric field intensity map that shows negative intensity over time.
![Question1](https://github.com/user-attachments/assets/0a1befb8-1845-4b0a-9e20-37a488fe6ee6)

What I understand:
A single macro particle moves to the negative side on the X-axis.
Step shapes in the Ex field follow the positions of the electron density.
There are small gradations at the end of the Ex field, which follow the electron density profile of the single macro electron particle.
The Ex field due to the movement of a single macro particle will continue to update in the direction the macro particle moves, and the sum of the Ex field intensity will remain the same.
This can numerically be explained by equations related to the Poisson equation.
![Question3](https://github.com/user-attachments/assets/bbecd1c6-5d8a-4763-a1ed-7a70aa83e4bf)
![Question2](https://github.com/user-attachments/assets/bbbc44e9-a34d-487c-84ee-affa971e4569)

My problem:
The results of the 1D PIC simulation do not match with the equations I know for the 'electric field from moving particles' or the 'electric field from the Poisson equation and Gauss's law'. Can I get a hint on how a 1D PIC updates the EM field by particle?

Thank you for your help!

**Comment by TomGoffrey** [comment]
I'll keep my answer brief, because I think a full explanation of plasma physics is beyond the scope of this forum.

1. EPOCH evolves the EM fields according to Maxwell's equations. Specifically it uses Ampere's law and Faraday's law.
2. The particle positions and momenta are updated by solving the Lorentz force, and the EM fields. The resulting current density is then calculated, and this is used to update the EM fields. This process is then repeated.
3. The equations you quote are electrostatic. EPOCH is an electromagnetic code.
4. Whilst Gauss' for the EM field is not used explicitly in the code, these are constraints on your initial fields. If you initialise the simulation as you describe (single electron species, zero initial electric field) you are implicitly specifying a stationary neutralising background of ions. If you want to simulate an electron species without such a background you have to also provide a consistent initial electric field.
