### ISSUE TITLE
field ionization of compound (such as SiO2)

### ISSUE THREAD

**Issue by xh-ui** [Warwick-Plasma/epoch#682]
Dear all,

I want to simulate the field ionization of SiO2.    Is it OK just to set the atom fraction to be 1:2 ?     Is the energy gap,or say the ionisation and binding energies of such kind of compound included in EPOCH physics_packages/TABLES directory？

@Status-Mirror
Thank you!

**Comment by Status-Mirror** [comment]
Hi @xh-ui,

The EPOCH ionisation routines consider isolated atoms instead of molecules. To simulate field ionisation of SiO2, you should define separate Si and O species.

To show how this is done, I have modified the [field ionisation demo](https://epochpic.github.io/quickstart/basic_examples/ionisation.html#field-ionisation) in our documentation. If we assume SiO2 has a density of 2650 kg/m³, and an SiO2 molecule has a mass of 60u, then SiO2 has a number density of $2.7\times 10^{28} \text{ m}^{-3}$. For each molecule, there is 1 Si and 2 O, so the densities for these species are: $2.7\times 10^{28} \text{ m}^{-3}$ and $5.3\times 10^{28} \text{ m}^{-3}$ respectively.

A simple input deck would take the following form:

```
begin:control
  nx = 128
  npart = 20 * nx
  t_end = 42.4e-15
  x_min = 0
  x_max = 4.0e-6
  field_ionisation = T
end:control

begin:boundaries
  bc_x_min = simple_laser
  bc_x_max = open
end:boundaries

begin:laser
  boundary = x_min
  intensity = 3.0e15 * 1.0e4
  lambda = 800.0e-9
  t_profile = 1
  t_end = 10.7e-15
end:laser

begin:species
  name = Si
  charge = 0
  atomic_no = 14
  mass = 1836.2 * 28.0
  frac = 0.5
  rho = if ((x lt 3.30e-6) and (x gt 3.05e-6), 2.7e28, 0)
  ionise = T
  electron_species = Electron
end:species

begin:species
  name = O
  charge = 0
  atomic_no = 8
  mass = 1836.2 * 16.0
  frac = 0.5
  rho = if ((x lt 3.30e-6) and (x gt 3.05e-6), 5.3e28, 0)
  ionise = T
  electron_species = Electron
end:species

begin:species
  name = Electron
  frac = 0
  identify:electron
end:species

begin:output
  dt_snapshot = t_end/100
  number_density = always + species
end:output
```

Hope this helps,
Stuart

**Comment by Hnair13** [comment]
Hello @Status-Mirror in this given input deck don't we have to specify the electron properties in another species block?

**Comment by Status-Mirror** [comment]
Hi @Hnair13,

We do specify the electron properties, here:

```
begin:species
  name = Electron
  frac = 0
  identify:electron
end:species
```

In the input deck I provide, we start with neutral non-ionised silicon and oxygen - there are no free electrons in the system we need to load. As the target is ionised, the ionisation routines will start to populate our empty `Electron` species with ejected macro-electrons.

Cheers,
Stuart

**Comment by TomGoffrey** [comment]
Just to add, from a not particularly rigorous search, the disassociation energy of SiO2 is lower than the ionisation energies of their constituent parts (although possibly not dramatically so), so the approach @Status-Mirror suggests is reasonable.

**Comment by xh-ui** [comment]
Thank you for your answer. I think I have understanded it.
